services:
  # db:
  #   image: postgres:16-alpine
  #   restart: unless-stopped
  #   environment:
  #     POSTGRES_USER: approval_user
  #     POSTGRES_PASSWORD: mysecretpassword
  #     POSTGRES_DB: approval_db
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - approval_db_data:/var/lib/postgresql/data
  #   healthcheck:
  #     test: ["CMD-SHELL", "pg_isready -U approval_user -d approval_db"]
  #     interval: 5s
  #     timeout: 5s
  #     retries: 10

  backend:
    build: ./backend
    restart: unless-stopped
    # depends_on:
    #   db:
    #     condition: service_healthy
    environment:
      DATABASE_URL: "postgresql://postgres.qfvtnhygzxnjspjijyts:87fkuc6pqs7kYkS1@aws-0-eu-west-1.pooler.supabase.com:5432/postgres"
      JWT_SECRET: "a7U1HPiLf7eZJiv+YSU8jYM5XdolNd99+ZF1biIQN0E="
      JWT_EXPIRES_IN: "8h"
      PORT: 4000
      UPLOAD_DIR: uploads
      MAX_UPLOAD_BYTES: 5242880
      NODE_ENV: production
    ports:
      - "4000:4000"
    volumes:
      - approval_uploads:/app/uploads
  
  caddy:
    image: caddy:2-alpine
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
    depends_on:
      - backend


volumes:
  approval_db_data:
  approval_uploads:
  caddy_data:
